config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'user_skills#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :user_skills, only:[:show] do
    resources :bookings, only:[:create]
  end

  resources :bookings, only:[:index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user_skill
  belongs_to :user

  validates :review, presence: true, on: :update
  validates :rating, presence: true, on: :update
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills
  has_many :users, through: :user_skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_skills
  has_many :bookings
  has_many :skills, through: :user_skills
  validates :email, presence: true
  # validates :address, presence: true
  # validates :name, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :skill
  belongs_to :user
  has_many :bookings
  validates :user, uniqueness: {scope: :skill}

  def average_rating
    bookings.average(:rating).to_i
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
    # @book = Booking.find(@tt)
  end

  def create
    @user_skill = UserSkill.find(params[:user_skill_id])
    @booking = @user_skill.bookings.new(booking_params)
    @booking.user = current_user
    @booking.save
    redirect_to bookings_path
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      respond_to do |format|
        format.html { redirect_to bookings_path }
        format.js # render update.js.erb
      end
    else
      @bookings = current_user.bookings
      respond_to do |format|
        format.html { render :index }
        format.js # render update.js.erb
      end
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:user_skill_id, :user_id, :happenned_at, :review, :rating)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      redirect_to skills_show_path(@skill)
    else
      render :new
    end
  end

  private

  def skill_params
    params.require(:skill).permit(:name, :description, :picture, :icon)
  end

end

app/controllers/user_skills_controller.rb
class UserSkillsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

   def index
    @user = User.all
    @users = @user.where.not(latitude: nil, longitude: nil)
      @markers = @users.map do |us|
        {
          lat: us.latitude,
          lng: us.longitude#,
          }
      end
    @skills = Skill.all
    @selected_user_skills = UserSkill.all
    @selected_user_skills = UserSkill.where(user_id: params[:user_id]) if params[:user_id]
    @user_skills = UserSkill.all
   end

   def show

    @user_skill = UserSkill.find(params[:id])
    @booking = Booking.new
    @user_latitude = @user_skill.user.latitude
    @user_longitude = @user_skill.user.longitude
    @markers = [{lat: @user_skill.user.latitude, lng: @user_skill.user.longitude}]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_format(datetime)
  datetime.strftime('%H:%M') unless datetime.blank?
  end
end

app/views/bookings/_booking.html.erb
<div class="col-sm-12 list-card-booking">
  <div class="col-sm-8">
    <div class="list-card-top">
      <%= cl_image_tag booking.user_skill.user.avatar, class: "avatar"%>
      <h4><%= booking.user_skill.user.name %></h4>
    </div>
    <p><%= raw "<i class='fa fa-star'></i>" * booking.rating.to_i %></p>
    <p class="review"><%= booking.review %></p>
    <p class="date-review" ><%= booking.happenned_at%></p>
  </div>
  <% if booking.review == nil &&  booking.happenned_at < Date.today || booking.errors.any?  %>
    <div class="col-sm-4 form-list-card-booking">
      <%= simple_form_for booking, class: 'margin-form', remote: true do |f| %>
        <%= f.collection_radio_buttons :rating,
          [[1, '.'],  [2 , "."],[3,"." ],[4,"." ],[5, "."]],
          :first,
          :last,
          item_first_class: "custom",
          item_wrapper_class: "custom-radio",:input_html =>
           { :checked => true }
        %>
        <% if booking.errors.any? && booking.rating.nil? %>
          <p class="text-danger">You must set a rating</p>
        <% end %>
        <%= f.input :review %>
        <%= f.submit "Add a Rewiew" %>
      <% end %>
    </div>
  <% elsif  booking.review != nil %>
    <p class="commented">you have already commented</p>
  <% else %>
    <p class="not-yet">You can not comment yet</p>
  <% end %>
</div>

app/views/bookings/index.html.erb
<h1 class="chg-color marge-left-title">Your bookings</h1>
<div class="container">
  <% @bookings.each do |booking| %>
    <div id="booking-<%= booking.id %>">
      <%= render "booking", booking: booking %>
    </div>
  <% end %>
</div>

app/views/bookings/update.js.erb
// on va cahercher le bon id booking
var booking = document.getElementById('booking-<%= @booking.id %>');
// on re render l'intérieur de cette carte de booking
booking.innerHTML = "<%= j render "booking", booking: @booking %>";

app/views/layouts/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(168,101,0,0.2) 0%, rgba(0,36,61,0.3) 50%), url('<%= cl_image_path("banner-2.jpg") %>');">
  <div class="banner-content">
    <h1>Got's mentors</h1>
    <p>Discover your hidden face !!</p>
  </div>
</div>

app/views/layouts/_card.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/copenhagen');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Le Wagon Copenhagen</h2>
          <p>Very cool city, the best</p>
        </div>
        <img class="card-user avatar" src="https://kitt.lewagon.com/placeholder/users/atmosfeer">
        <a class="card-link" href="#" ></a>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/lisbon');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Le Wagon Lisbon</h2>
          <p>Very cool city, the best</p>
        </div>
        <img class="card-user avatar" src="https://kitt.lewagon.com/placeholder/users/graysdays">
        <a class="card-link" href="#" ></a>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
     <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/sao-paulo');">
       <div class="card-category">Popular</div>
       <div class="card-description">
         <h2>Le Wagon Sao Paulo</h2>
         <p>Very cool city, the best</p>
       </div>
       <img class="card-user avatar" src="https://kitt.lewagon.com/placeholder/users/matleroux">
       <a class="card-link" href="#" ></a>
     </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo.png" %>
  </a>
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% unless user_signed_in? %>
      <%= link_to(new_user_registration_path, { :class =>"navbar-wagon-item navbar-wagon-link" }) do %>
         S'inscrire
         <% end %> -
      <%= link_to(user_session_path, { :class =>"navbar-wagon-item navbar-wagon-link" }) do %>
         Se connecter
         <% end %>
    <% end %>
    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle border-user" id="navbar-wagon-menu" data-toggle="dropdown">
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "My Bookings", bookings_path, method: :get %></li>
            <li><%= link_to "Profile", user_registration_path, method: :patch %></a></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "My Bookings", bookings_path, method: :get %></li>
        <li><%= link_to "Profile", user_registration_path, method: :patch %></a></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MentorAid</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Cinzel+Decorative:700,900|Raleway:400,600" rel="stylesheet">
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <% if notice %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyBXZ7_e2ppVBqTL2pHxmp9iQFsR2gOa5ow" %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<% @users.each do |user| %>
  <%= user.pseudo %>
<% end %>

app/views/user_skills/_filtres.html.erb
<div class="filtres">
  <% @user_skills.each do |user_skill| %>
    <div class="icon">
      <%= link_to root_path(user_id: user_skill.user_id) do %>
        <i class="<%= user_skill.skill.icon %>"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/user_skills/index.html.erb
<%= render "layouts/banner"%>
<div class="wrapper">
  <div class="container-fluid">
    <%= render "user_skills/filtres" %>
    <div class="row">
      <% @selected_user_skills.each do |user_skill| %>
        <div class="col-xs-12 col-sm-4">
          <%= link_to user_skill_path(user_skill.id) do %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.6)), url('<%= cl_image_path user_skill.skill.picture, height: 300, width: 400, crop: :fill %>');">
              <div class="card-category"><p><%=user_skill.user.name%></p></div>
              <div class="card-description">
                <h6><%= user_skill.skill.name %></h6>
              </div>
              <%= cl_image_tag(user_skill.user.avatar, :gravity=>"face", :height=>80, :width=>80, :x=>0, :crop=>"fill", class: "card-user avatar border-user") %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div id="map" data-markers="<%= @markers.to_json %>"></div>
</div>

app/views/user_skills/show.html.erb
<div id="map" style="width: 100%; height: 450px;" data-markers="<%= @markers.to_json %>"></div>
<h2 style="text-align: center;" class="chg-color"> <strong>User Skill Details</strong> </h2>
<div class="container-fluid ">
  <div class="row">
    <div class="col-xs-12 >
      <div class="list-unstyled ">
        <div class="product">
          <div class="product-upvote">
            <p><%= raw "<i class='fa fa-star'></i>" * @user_skill.average_rating.to_i %></p>
          </div>
          <%= cl_image_tag( @user_skill.user.avatar, :gravity=>"face", class: "img-rounded border-user", :height=>80, :width=>80, :x=>0, :crop=>"fill") %>
          <div class="product-description">
            <h3><strong><%= @user_skill.skill.name%></strong></h3>
            <p><%= @user_skill.skill.description%></p>
          </div>
          <%= simple_form_for [@user_skill, @booking ] do |f| %>
            <%= f.input :happenned_at, as: :date, order: [:day, :month, :year] %>
            <%= f.submit "reserver" %>
          <% end %>

        </div>
    </div>
    <div class= "all-reviews col-xs-12">
    <% @user_skill.bookings.each do |booking|%>
    <div class="product2">
      <h4><%= booking.user.name %></h4>
      <p><%= booking.review %></p>
    </div>
    <%end%>
    </div>
    </div>
  </div>
</div>